C Linux: src/C-Unix-STD-Signal-Fork-Kill/main.c File Reference
main.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <signal.h>
#include <unistd.h>
Functions
void handler (int sig)
int main (int argc, char **argv)
Function Documentation
handler()
void handler (int sig)
Definition at line 6 of file main.c.
{
    printf("Ricevuto segnale %d\n", sig);
    if(sig==SIGUSR1)
    {
        kill(getppid(), SIGUSR2);
    }
    else if(sig==SIGUSR2)
    {
        kill(getppid(), SIGUSR1);
    }
    else if(sig==SIGINT)
    {
        kill(getppid(), SIGINT);
    }
    return;
}
Referenced by main(), and main().
main()
int main (int argc, char ** argv)
Definition at line 24 of file main.c.
{
    int i, j, *s;
    pid_t child;
    s=malloc((argc-1)*sizeof(int));
    for(i=1; i<argc; i++)
    {
        j=i-1;
        s[j]=atoi(argv[i]);
    }
    i=0;
    (void)signal(SIGUSR1, handler);
    (void)signal(SIGUSR2, handler);
    (void)signal(SIGINT, handler);
    child=fork();
    if(child==-1)
    {
        fprintf(stderr, "Errore fork");
        exit(0);
    }
    else if(child==0)
    {
        while(0==0)
        {
            pause();
        }
    }
    else
    {
        while(i!=5) //ciclo infinito del padre
        {
            sleep(1);
            kill(child, s[i]);
            i++;
            if(i>(argc-1)) i=0;
        }
    }
    free(s);
    free(s);
    return 0;
}
References handler().
⬇️ Download 🐙 View on GitHub
© 2025 Giuseppe Pedone — GitHub