var searchData=
[
  ['a_0',['a',['../C-Unix-STD-Signal_2main_8c.html#aa4c2a5552e9bc49b1816ff532f558c74',1,'main.c']]],
  ['a_20—_20download_20zip_1',['Option A — Download ZIP',['../md_Usage_2ADMINISTRATOR__GUIDE.html#autotoc_md84',1,'']]],
  ['a_20bug_2',['Use Case 3 — Report a Bug',['../md_Usage_2USECASES.html#autotoc_md131',1,'']]],
  ['a_20feature_3',['How to use a feature',['../md_Usage_2USER__GUIDE.html#autotoc_md141',1,'']]],
  ['a_20namespace_3a_4',['To add a namespace:',['../namespacecode.html#autotoc_md110',1,'']]],
  ['a_20pull_20request_5',['How to Open a Pull Request',['../md_README.html#autotoc_md56',1,'']]],
  ['a_20version_20includes_6',['🚀 What a Version Includes',['../md_Version_2VERSION.html#autotoc_md227',1,'']]],
  ['about_20new_20features_7',['About New Features',['../md_Version_2FEATURE.html#autotoc_md189',1,'']]],
  ['about_20next_20features_8',['About Next Features',['../md_Version_2FEATURE.html#autotoc_md190',1,'']]],
  ['about_20the_20project_9',['About the Project',['../md_PROJECT.html#autotoc_md8',1,'']]],
  ['about_20the_20project_20🎯_10',['About the Project 🎯',['../md_README.html#autotoc_md26',1,'']]],
  ['access_20as_20administrator_11',['How to access as administrator',['../md_Usage_2ADMINISTRATOR__GUIDE.html#autotoc_md96',1,'']]],
  ['accessibility_12',['🔐 Accessibility',['../md_Version_2API.html#autotoc_md150',1,'']]],
  ['acknowledgements_13',['Acknowledgements',['../md_README.html#autotoc_md67',1,'']]],
  ['actor_20types_14',['Actor Types',['../md_Usage_2ACTORS.html#autotoc_md68',1,'']]],
  ['actors_15',['actors',['../md_Usage_2USECASES.html#autotoc_md128',1,'Actors'],['../md_Usage_2ACTORS.html',1,'ACTORS']]],
  ['actors_20🎮_16',['Usage and Actors 🎮',['../md_README.html#autotoc_md42',1,'']]],
  ['actors_2emd_17',['ACTORS.md',['../ACTORS_8md.html',1,'']]],
  ['add_20a_20namespace_3a_18',['To add a namespace:',['../namespacecode.html#autotoc_md110',1,'']]],
  ['address_20apis_20through_20namespaces_19',['🧩 How To Address APIs through Namespaces',['../md_Version_2NAMESPACE.html#autotoc_md211',1,'']]],
  ['administration_20lifecycle_20',['Administration LifeCycle',['../md_Usage_2ADMINISTRATOR__GUIDE.html#autotoc_md79',1,'']]],
  ['administration_20overview_21',['Administration Overview',['../md_Usage_2ADMINISTRATOR__GUIDE.html#autotoc_md78',1,'']]],
  ['administration_20tasks_22',['Administration Tasks',['../md_Usage_2ADMINISTRATOR__GUIDE.html#autotoc_md80',1,'']]],
  ['administrator_23',['administrator',['../md_Usage_2ACTORS.html#autotoc_md69',1,'1. Administrator'],['../md_Usage_2ADMINISTRATOR__GUIDE.html#autotoc_md96',1,'How to access as administrator']]],
  ['administrator_20role_24',['Administrator Role',['../md_Usage_2ROLES.html#autotoc_md119',1,'']]],
  ['administrator_5fguide_25',['ADMINISTRATOR_GUIDE',['../md_Usage_2ADMINISTRATOR__GUIDE.html',1,'']]],
  ['administrator_5fguide_2emd_26',['ADMINISTRATOR_GUIDE.md',['../ADMINISTRATOR__GUIDE_8md.html',1,'']]],
  ['advantages_27',['Advantages',['../md_PROJECT.html#autotoc_md14',1,'']]],
  ['advantages_20of_20the_20doxygen_20site_28',['Advantages of the Doxygen Site',['../md_PROJECT.html#autotoc_md17',1,'']]],
  ['alpha_20version_29',['1.2 Alpha-Version',['../md_Version_2VERSION.html#autotoc_md234',1,'']]],
  ['also_30',['also',['../md_Version_2BUG.html#autotoc_md172',1,'See Also'],['../md_Version_2RELEASE__POLICY.html#autotoc_md222',1,'See Also'],['../md_Version_2API.html#autotoc_md164',1,'See Also'],['../md_Version_2CHANGELOG.html#autotoc_md179',1,'See Also'],['../md_Version_2VERSION.html#autotoc_md244',1,'See Also'],['../md_Version_2FEATURE.html#autotoc_md191',1,'See Also'],['../md_Version_2FIX.html#autotoc_md200',1,'See Also'],['../md_Usage_2USECASES.html#autotoc_md133',1,'See Also'],['../md_Version_2NAMESPACE.html#autotoc_md212',1,'See Also'],['../md_Usage_2ROLES.html#autotoc_md124',1,'See Also'],['../md_PROJECT.html#autotoc_md21',1,'See Also'],['../md_Usage_2ACTORS.html#autotoc_md74',1,'See Also'],['../md_README.html#autotoc_md62',1,'See Also']]],
  ['an_20issue_31',['How to Open an Issue',['../md_README.html#autotoc_md59',1,'']]],
  ['and_20actors_20🎮_32',['Usage and Actors 🎮',['../md_README.html#autotoc_md42',1,'']]],
  ['and_20contribute_20to_20project_33',['Use Case 2 — Fork and Contribute to Project',['../md_Usage_2USECASES.html#autotoc_md130',1,'']]],
  ['and_20dependencies_34',['Prerequisites and Dependencies',['../md_Usage_2ADMINISTRATOR__GUIDE.html#autotoc_md81',1,'']]],
  ['api_35',['API',['../md_Version_2API.html',1,'']]],
  ['api_20development_20🧠_36',['API Development 🧠',['../md_Usage_2DEVELOPMENT__GUIDE.html#autotoc_md108',1,'']]],
  ['api_20reference_37',['API Reference',['../md_Version_2API.html#autotoc_md153',1,'']]],
  ['api_2emd_38',['API.md',['../API_8md.html',1,'']]],
  ['apis_39',['apis',['../md_Version_2API.html#autotoc_md163',1,'How To Develop APIs'],['../namespacemyNamespace.html#autotoc_md114',1,'How to extend APIs'],['../md_Version_2API.html#autotoc_md162',1,'How To Integrate APIs']]],
  ['apis_20through_20namespaces_40',['🧩 How To Address APIs through Namespaces',['../md_Version_2NAMESPACE.html#autotoc_md211',1,'']]],
  ['architecture_41',['🚀 Architecture',['../md_PROJECT.html#autotoc_md10',1,'']]],
  ['as_20administrator_42',['How to access as administrator',['../md_Usage_2ADMINISTRATOR__GUIDE.html#autotoc_md96',1,'']]],
  ['attribution_43',['Attribution',['../md_CODE__OF__CONDUCT.html#autotoc_md6',1,'']]],
  ['authors_20🧑‍💻_44',['Authors 🧑‍💻',['../md_README.html#autotoc_md66',1,'']]]
];
