var searchData=
[
  ['case_201_20—_20generate_20project_20documentation_0',['Use Case 1 — Generate Project Documentation',['../md_Usage_2USECASES.html#autotoc_md129',1,'']]],
  ['case_202_20—_20fork_20and_20contribute_20to_20project_1',['Use Case 2 — Fork and Contribute to Project',['../md_Usage_2USECASES.html#autotoc_md130',1,'']]],
  ['case_203_20—_20report_20a_20bug_2',['Use Case 3 — Report a Bug',['../md_Usage_2USECASES.html#autotoc_md131',1,'']]],
  ['case_204_20—_20update_20project_20version_3',['Use Case 4 — Update Project Version',['../md_Usage_2USECASES.html#autotoc_md132',1,'']]],
  ['cd_20role_20optional_4',['CI/CD Role (Optional)',['../md_Usage_2ROLES.html#autotoc_md122',1,'']]],
  ['cd_20system_20optional_5',['4. CI/CD System (Optional)',['../md_Usage_2ACTORS.html#autotoc_md72',1,'']]],
  ['change_20log_6',['🔄 Change Log',['../md_Version_2CHANGELOG.html#autotoc_md178',1,'']]],
  ['change_20log_20📋_7',['Change Log 📋',['../md_README.html#autotoc_md46',1,'']]],
  ['changelog_8',['CHANGELOG',['../md_Version_2CHANGELOG.html',1,'']]],
  ['changelog_2emd_9',['CHANGELOG.md',['../CHANGELOG_8md.html',1,'']]],
  ['changes_10',['changes',['../md_Version_2API.html#autotoc_md151',1,'↩️ Changes'],['../md_Version_2CHANGELOG.html#autotoc_md177',1,'🔧 Types of Changes']]],
  ['characteristics_11',['Characteristics',['../md_Version_2API.html#autotoc_md146',1,'']]],
  ['ci_20cd_20role_20optional_12',['CI/CD Role (Optional)',['../md_Usage_2ROLES.html#autotoc_md122',1,'']]],
  ['ci_20cd_20system_20optional_13',['4. CI/CD System (Optional)',['../md_Usage_2ACTORS.html#autotoc_md72',1,'']]],
  ['clone_20repository_14',['Option B — Clone Repository',['../md_Usage_2ADMINISTRATOR__GUIDE.html#autotoc_md85',1,'']]],
  ['code_15',['code',['../namespacecode.html',1,'']]],
  ['code_20integration_16',['3️⃣ Source Code Integration',['../md_PROJECT.html#autotoc_md18',1,'']]],
  ['code_20of_20conduct_17',['code of conduct',['../md_README.html#autotoc_md61',1,'4. Code of Conduct'],['../md_CODE__OF__CONDUCT.html',1,'Contributor Covenant Code of Conduct']]],
  ['code_20structure_20🧩_18',['Code Structure 🧩',['../md_Usage_2DEVELOPMENT__GUIDE.html#autotoc_md105',1,'']]],
  ['code_5fof_5fconduct_2emd_19',['CODE_OF_CONDUCT.md',['../CODE__OF__CONDUCT_8md.html',1,'']]],
  ['collection_20',['🧩 Collection',['../md_Version_2API.html#autotoc_md149',1,'']]],
  ['command_21',['command',['../md_Version_2NAMESPACE.html#autotoc_md207',1,'📎 Command'],['../md_Version_2API.html#autotoc_md155',1,'Command']]],
  ['conduct_22',['conduct',['../md_README.html#autotoc_md61',1,'4. Code of Conduct'],['../md_CODE__OF__CONDUCT.html',1,'Contributor Covenant Code of Conduct']]],
  ['configuration_23',['configuration',['../md_README.html#autotoc_md37',1,'⚙️ Configuration'],['../md_Usage_2ADMINISTRATOR__GUIDE.html#autotoc_md90',1,'Configuration'],['../md_Usage_2ADMINISTRATOR__GUIDE.html#autotoc_md98',1,'How to update configuration']]],
  ['contact_20us_20☎️_24',['contact us ☎️',['../md_Version_2NAMESPACE.html#autotoc_md214',1,'Contact us ☎️'],['../md_Version_2FIX.html#autotoc_md202',1,'Contact us ☎️'],['../md_Version_2FEATURE.html#autotoc_md193',1,'Contact us ☎️'],['../md_Version_2CHANGELOG.html#autotoc_md181',1,'Contact us ☎️'],['../md_Version_2BUG.html#autotoc_md174',1,'Contact us ☎️'],['../md_Version_2API.html#autotoc_md166',1,'Contact us ☎️'],['../md_Version_2RELEASE__POLICY.html#autotoc_md224',1,'Contact us ☎️'],['../md_README.html#autotoc_md64',1,'Contact us ☎️'],['../md_Usage_2USER__GUIDE.html#autotoc_md144',1,'Contact Us ☎️'],['../md_Usage_2USECASES.html#autotoc_md135',1,'Contact us ☎️'],['../md_Version_2VERSION.html#autotoc_md246',1,'Contact us ☎️'],['../md_PROJECT.html#autotoc_md23',1,'Contact us ☎️'],['../md_Usage_2ROLES.html#autotoc_md126',1,'Contact us ☎️'],['../md_Usage_2ADMINISTRATOR__GUIDE.html#autotoc_md101',1,'Contact us ☎️'],['../md_Usage_2ACTORS.html#autotoc_md76',1,'Contact us ☎️'],['../namespacemyNamespace.html#autotoc_md117',1,'Contact Us ☎️']]],
  ['contact_5fus_25',['CONTACT_US',['../md_CONTACT__US.html',1,'']]],
  ['contact_5fus_2emd_26',['CONTACT_US.md',['../CONTACT__US_8md.html',1,'']]],
  ['contents_27',['contents',['../md_README.html#autotoc_md25',1,'📓 Table of Contents'],['../md_Usage_2DEVELOPMENT__GUIDE.html#autotoc_md102',1,'📓 Table of Contents'],['../md_Version_2FEATURE.html#autotoc_md183',1,'📓 Table of Contents'],['../md_Version_2FIX.html#autotoc_md195',1,'📓 Table of Contents'],['../md_Usage_2ADMINISTRATOR__GUIDE.html#autotoc_md77',1,'📓 Table of Contents'],['../md_Version_2CHANGELOG.html#autotoc_md176',1,'📓 Table of Contents'],['../md_Version_2RELEASE__POLICY.html#autotoc_md216',1,'📓 Table of Contents'],['../md_Version_2BUG.html#autotoc_md168',1,'📓 Table of Contents'],['../md_Version_2API.html#autotoc_md145',1,'📓 Table of Contents'],['../md_Usage_2USER__GUIDE.html#autotoc_md136',1,'📓 Table of Contents'],['../md_PROJECT.html#autotoc_md7',1,'📓 Table of Contents'],['../md_Version_2NAMESPACE.html#autotoc_md204',1,'📓 Table of Contents'],['../md_README.html#autotoc_md51',1,'Table of Contents'],['../md_Version_2VERSION.html#autotoc_md226',1,'Table of Contents']]],
  ['contribute_20to_20project_28',['Use Case 2 — Fork and Contribute to Project',['../md_Usage_2USECASES.html#autotoc_md130',1,'']]],
  ['contributing_20👋_29',['Contributing 👋',['../md_README.html#autotoc_md50',1,'']]],
  ['contribution_20rules_30',['General Contribution Rules',['../md_README.html#autotoc_md52',1,'']]],
  ['contributor_20covenant_20code_20of_20conduct_31',['Contributor Covenant Code of Conduct',['../md_CODE__OF__CONDUCT.html',1,'']]],
  ['control_32',['control',['../md_Version_2NAMESPACE.html#autotoc_md206',1,'📎 Control'],['../md_Version_2API.html#autotoc_md154',1,'Control']]],
  ['conventions_33',['Naming conventions',['../md_Usage_2DEVELOPMENT__GUIDE.html#autotoc_md106',1,'']]],
  ['copia_34',['copia',['../Es2_8c.html#ad9e977b3c72a6680e4588e296647cd92',1,'Es2.c']]],
  ['covenant_20code_20of_20conduct_35',['Contributor Covenant Code of Conduct',['../md_CODE__OF__CONDUCT.html',1,'']]]
];
