var searchData=
[
  ['readfilein_0',['ReadFileIn',['../C-Unix-STD-Threads-Files-Assert_2main_8c.html#ae076966ba86ec537886a5ae77b8c232c',1,'main.c']]],
  ['readme_1',['README',['../md_README.html',1,'']]],
  ['readme_2emd_2',['README.md',['../README_8md.html',1,'']]],
  ['reference_3',['reference',['../md_Version_2API.html#autotoc_md153',1,'API Reference'],['../md_Version_2FEATURE.html#autotoc_md184',1,'Feature Reference'],['../md_Version_2NAMESPACE.html#autotoc_md205',1,'Namespace Reference']]],
  ['registration_4',['🗂️ Version Registration',['../md_Version_2VERSION.html#autotoc_md230',1,'']]],
  ['release_5',['release',['../md_Version_2VERSION.html#autotoc_md232',1,'1. Pre-Release'],['../md_Version_2VERSION.html#autotoc_md235',1,'2. Release']]],
  ['release_20policy_20📜_6',['release policy 📜',['../md_Version_2VERSION.html#autotoc_md243',1,'Release Policy 📜'],['../md_README.html#autotoc_md44',1,'Release Policy 📜']]],
  ['release_20policy_20standard_7',['Release Policy Standard',['../md_Version_2RELEASE__POLICY.html#autotoc_md217',1,'']]],
  ['release_5fpolicy_8',['RELEASE_POLICY',['../md_Version_2RELEASE__POLICY.html',1,'']]],
  ['release_5fpolicy_2emd_9',['RELEASE_POLICY.md',['../RELEASE__POLICY_8md.html',1,'']]],
  ['releases_20⭐_10',['Releases ⭐',['../md_README.html#autotoc_md43',1,'']]],
  ['report_20a_20bug_11',['Use Case 3 — Report a Bug',['../md_Usage_2USECASES.html#autotoc_md131',1,'']]],
  ['repository_12',['Option B — Clone Repository',['../md_Usage_2ADMINISTRATOR__GUIDE.html#autotoc_md85',1,'']]],
  ['request_13',['How to Open a Pull Request',['../md_README.html#autotoc_md56',1,'']]],
  ['request_20guidelines_14',['Pull Request Guidelines',['../md_README.html#autotoc_md57',1,'']]],
  ['requests_15',['2. Pull Requests',['../md_README.html#autotoc_md55',1,'']]],
  ['responsibilities_16',['responsibilities',['../md_Usage_2DEVELOPMENT__GUIDE.html#autotoc_md107',1,'Developer responsibilities'],['../md_CODE__OF__CONDUCT.html#autotoc_md3',1,'Our Responsibilities']]],
  ['restart_20the_20system_17',['How to restart the system',['../md_Usage_2ADMINISTRATOR__GUIDE.html#autotoc_md97',1,'']]],
  ['role_18',['role',['../md_Usage_2ROLES.html#autotoc_md119',1,'Administrator Role'],['../md_Usage_2ROLES.html#autotoc_md120',1,'Developer Role'],['../md_Usage_2ROLES.html#autotoc_md121',1,'User Role']]],
  ['role_20optional_19',['CI/CD Role (Optional)',['../md_Usage_2ROLES.html#autotoc_md122',1,'']]],
  ['role_20permissions_20',['Role Permissions',['../md_Usage_2ROLES.html#autotoc_md123',1,'']]],
  ['roles_21',['ROLES',['../md_Usage_2ROLES.html',1,'']]],
  ['roles_20description_22',['Roles Description',['../md_Usage_2ROLES.html#autotoc_md118',1,'']]],
  ['roles_2emd_23',['ROLES.md',['../ROLES_8md.html',1,'']]],
  ['rules_24',['rules',['../md_README.html#autotoc_md52',1,'General Contribution Rules'],['../md_Version_2RELEASE__POLICY.html#autotoc_md221',1,'Versioning Grammar Rules'],['../md_Version_2RELEASE__POLICY.html#autotoc_md220',1,'Versioning Precedence Rules']]],
  ['rules_20📘_25',['Versioning Rules 📘',['../md_Version_2RELEASE__POLICY.html#autotoc_md219',1,'']]],
  ['run_26',['🚀 Run',['../md_README.html#autotoc_md39',1,'']]]
];
