var searchData=
[
  ['dependencies_0',['dependencies',['../md_README.html#autotoc_md30',1,'📦 Dependencies'],['../md_Usage_2ADMINISTRATOR__GUIDE.html#autotoc_md81',1,'Prerequisites and Dependencies']]],
  ['dependencies_20verification_1',['💡 Dependencies Verification',['../md_README.html#autotoc_md34',1,'']]],
  ['dependency_20verification_2',['Dependency Verification',['../md_Usage_2ADMINISTRATOR__GUIDE.html#autotoc_md82',1,'']]],
  ['deployment_3',['🌍 Deployment',['../md_README.html#autotoc_md40',1,'']]],
  ['deprecated_4',['3. Deprecated',['../md_Version_2VERSION.html#autotoc_md236',1,'']]],
  ['deprecation_20🔥_5',['Deprecation 🔥',['../md_Version_2VERSION.html#autotoc_md239',1,'']]],
  ['description_6',['Roles Description',['../md_Usage_2ROLES.html#autotoc_md118',1,'']]],
  ['develop_20apis_7',['How To Develop APIs',['../md_Version_2API.html#autotoc_md163',1,'']]],
  ['develop_20features_8',['How To Develop Features',['../md_Version_2FEATURE.html#autotoc_md188',1,'']]],
  ['developer_9',['2. Developer',['../md_Usage_2ACTORS.html#autotoc_md70',1,'']]],
  ['developer_20responsibilities_10',['Developer responsibilities',['../md_Usage_2DEVELOPMENT__GUIDE.html#autotoc_md107',1,'']]],
  ['developer_20role_11',['Developer Role',['../md_Usage_2ROLES.html#autotoc_md120',1,'']]],
  ['development_20🧠_12',['API Development 🧠',['../md_Usage_2DEVELOPMENT__GUIDE.html#autotoc_md108',1,'']]],
  ['development_20overview_20🧠_13',['Development Overview 🧠',['../md_Usage_2DEVELOPMENT__GUIDE.html#autotoc_md103',1,'']]],
  ['development_5fguide_14',['DEVELOPMENT_GUIDE',['../md_Usage_2DEVELOPMENT__GUIDE.html',1,'']]],
  ['development_5fguide_2emd_15',['DEVELOPMENT_GUIDE.md',['../DEVELOPMENT__GUIDE_8md.html',1,'']]],
  ['dim_16',['dim',['../C-Func-pointer_2main_8c.html#a4bf6a1e750d841477978a43a04c4f062',1,'main.c']]],
  ['directory_20tree_17',['directory tree',['../md_PROJECT.html#autotoc_md20',1,'📁 Directory Tree'],['../md_README.html#autotoc_md27',1,'Directory Tree']]],
  ['documentation_18',['documentation',['../md_PROJECT.html#autotoc_md11',1,'Markdown-based documentation'],['../md_Usage_2USECASES.html#autotoc_md129',1,'Use Case 1 — Generate Project Documentation']]],
  ['documentation_20generation_19',['Documentation Generation',['../md_Usage_2ADMINISTRATOR__GUIDE.html#autotoc_md92',1,'']]],
  ['documentation_20process_20',['How to start the documentation process',['../md_Usage_2USER__GUIDE.html#autotoc_md140',1,'']]],
  ['download_20zip_21',['Option A — Download ZIP',['../md_Usage_2ADMINISTRATOR__GUIDE.html#autotoc_md84',1,'']]],
  ['doxyfile_22',['Doxyfile',['../Doxyfile.html',1,'']]],
  ['doxyfile_3a_23',['Using Standard Doxyfile:',['../md_Usage_2ADMINISTRATOR__GUIDE.html#autotoc_md89',1,'']]],
  ['doxygen_20sh_20tt_20script_3a_24',['Using &lt;tt&gt;doxygen.sh&lt;/tt&gt; script:',['../md_Usage_2ADMINISTRATOR__GUIDE.html#autotoc_md87',1,'']]],
  ['doxygen_20site_25',['Advantages of the Doxygen Site',['../md_PROJECT.html#autotoc_md17',1,'']]],
  ['doxygen_20works_20in_20this_20template_26',['How Doxygen Works in This Template',['../md_PROJECT.html#autotoc_md16',1,'']]],
  ['doxygen_2eini_27',['doxygen.ini',['../doxygen_8ini.html',1,'']]],
  ['doxygen_2esh_28',['doxygen.sh',['../doxygen_8sh.html',1,'']]],
  ['doxygen_3a_29',['Using Doxygen:',['../md_Usage_2ADMINISTRATOR__GUIDE.html#autotoc_md93',1,'']]]
];
