CLinux: src/C-Func-pointer/main.c File Reference
main.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
Macros
#define dim 10
Typedefs
typedef void * tf
Functions
void inc (int a, void *b)
void * init ()
int main ()
void show (void *b)
void sub (int a, void *b)
Macro Definition Documentation
dim
#define dim 10
Definition at line 4 of file main.c.
Typedef Documentation
tf
typedef void* tf
Definition at line 5 of file main.c.
Function Documentation
inc()
void inc (int a, void * b)
Definition at line 14 of file main.c.
{
     int *v, i = 0;
     v=(int *)b;
     for(;i<dim;v[i++]+=a);
     return;
 }
References a, b, and dim.
Referenced by main().
init()
void* init ()
Definition at line 21 of file main.c.
             {
     int *v, i = 0;
     v=malloc(sizeof(int)*dim);
     for(;i<dim;v[i++]=0);
     return((void*)v);
 }
References dim.
Referenced by main().
main()
int main ()
Definition at line 39 of file main.c.
 {
     int *v;
     tf add, dec;
     add = &inc;
     dec = &sub;
     v=(int*)init();
     inc(2,v);
     sub(1,v);
     show(v);
     return 0;
 }
References inc(), init(), show(), and sub().
show()
void show (void * b)
Definition at line 7 of file main.c.
                   {
     int *v, i = 0;
     v=(int *)b;
     for(printf("Start\n");i<dim;printf("\nv[%d] = %d", i, v[i++]));
     return;
 }
References b, and dim.
Referenced by main().
sub()
void sub (int a, void * b)
Definition at line 30 of file main.c.
{
     int *v, i = 0;
     v=(int *)b;
     for(;i<dim;v[i++]-=a);
     return;
 }
References a, b, and dim.
Referenced by main().
⬇️ Download 🐙 View on GitHub
© 2025 Giuseppe Pedone — GitHub