CLinux: src/C-Unix-STD-Threads-Files-Assert/main.c File Reference
main.c File Reference
#include <unistd.h>
#include <stdlib.h>
#include <stdio.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <pthread.h>
#include <string.h>
#include <assert.h>
Classes
struct nf
Macros
#define N 50
Typedefs
typedef struct nf nomifile
Functions
void bubblesort (void *ptr)
void * funzione (void *ptr)
int main (int argc, char **argv)
void ReadFileIn (void *ptr)
void WriteFileOut (void *ptr)
Macro Definition Documentation
N
#define N 50
Definition at line 9 of file main.c.
Typedef Documentation
nomifile
typedef struct nf nomifile
Definition at line 23 of file main.c.
Function Documentation
bubblesort()
void bubblesort (void * ptr)
Definition at line 70 of file main.c.
 {
 int i, j, tmp;
 nomifile *arg=(nomifile *)ptr;
 for(i=1; i<arg->nr; i++){
 for(j=0; j<(arg->nr-i); j++)
 {
 if(arg->buf[j]>arg->buf[j+1])
 {
 tmp=arg->buf[j];
 arg->buf[j]=arg->buf[j+1];
 arg->buf[j+1]=tmp;
 }
 }
 }
 return;
 }
References nf::buf, and nf::nr.
Referenced by funzione().
funzione()
void* funzione (void * ptr)
Definition at line 32 of file main.c.
 {
 ReadFileIn(ptr);
 bubblesort(ptr);
 WriteFileOut(ptr);
 return NULL;
 }
References bubblesort(), ReadFileIn(), and WriteFileOut().
Referenced by main().
main()
int main (int argc, char ** argv)
Definition at line 136 of file main.c.
 {
 if((argc<=2)||(argc%2==0))  //Gli argomenti devono essere almeno 3 e sempre dispari
 {
     fprintf(stderr, "Errore negli argomenti!\n");
     exit(0);
 }
 int n=(argc-1)/2, i, j=1, err; //Il numero di thread è il numero di file/2
 pthread_t *tid;
 nomifile **v;
 tid=malloc(n*sizeof(pthread_t)); //Allocazione vettori
 v=malloc(n*sizeof(nomifile *));
 for(i=0; i<n; i++)
 v[i]=malloc(sizeof(nomifile));
 for(i=0; i<n; i++)  //Inizializzazione vettore struct
 {
 strcpy(v[i]->filein, argv[j]);
 j++;
 strcpy(v[i]->fileout, argv[j]);
 j++;
 err=pthread_create(&tid[i], NULL, funzione, v[i]);
 assert(err==0);
 }
 pthread_join(tid[n-1], NULL);
 return 0;
 }
References nf::filein, nf::fileout, funzione(), and n.
ReadFileIn()
void ReadFileIn (void * ptr)
Definition at line 43 of file main.c.
 {
 FILE *fin;
 int i;
 nomifile *arg=(nomifile *)ptr;
 fin=fopen(arg->filein, "r");
 fscanf(fin, "%d", &arg->nr);
 arg->buf=malloc((arg->nr)*sizeof(int));
 for(i=0; i<arg->nr; i++){
     fscanf(fin, "%d", &arg->buf[i]);
 }
 fclose(fin);
 return;
 }
References nf::buf, nf::filein, and nf::nr.
Referenced by funzione().
WriteFileOut()
void WriteFileOut (void * ptr)
Definition at line 108 of file main.c.
 {
 FILE *fout;
 int i;
 nomifile *arg=(nomifile *)ptr;
 fout=fopen(arg->fileout, "w");
 for(i=0; i<arg->nr; i++)
 {
 fprintf(fout, "%d\n", arg->buf[i]);
 }
 fclose(fout);
 return;
 }
References nf::buf, nf::fileout, and nf::nr.
Referenced by funzione().
⬇️ Download 🐙 View on GitHub
© 2025 Giuseppe Pedone — GitHub