CLinux: src/C-Unix-STD-Threads/main.c File Reference
main.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <fcntl.h>
#include <pthread.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
Classes
struct file
Macros
#define n(a) (a-1)/2
Typedefs
typedef struct file ftype
Functions
void main (int argc, char **argv)
void proc (char *inputfile, char *outputfile)
int * sort (int *buffer, int nr)
void * thread_function (void *arg)
Macro Definition Documentation
n
#define n (a) (a-1)/2
Definition at line 9 of file main.c.
Typedef Documentation
ftype
typedef struct file ftype
Definition at line 13 of file main.c.
Function Documentation
main()
void main (int argc, char ** argv)
Definition at line 15 of file main.c.
{
 ftype *v;
 pthread_t *tid;
 int r;
 int i_file=((argc>2)&&(argc%2!=0)?n(argc):-1);
 int i=0;
 int j=0;
 int r=0;
 if(i_file==-1)
 exit(-1);
 v=malloc(sizeof(ftype)*i_file);
 tid=malloc(sizeof(pthread_t)*i_file);
 while(i<i_file){
 tid[i]=i;
 v[i].input_file=malloc(sizeof(char)*strlen(argv[j]) + 1);
 strcpy(v[i].input_file,argv[j++]);
 v[i].output_file=malloc(sizeof(char)*strlen(argv[j]) + 1);
 strcpy(v[i++].output_file,argv[j++]);
 }
 for(i=0; i<i_file; i++, assert(r==0))
     r=pthread_create(&tid[i],NULL, thread_function, &v[i]);
     pthread_join(tid[i_file-1], NULL);
     return 0;
 }
References file::input_file, n, file::output_file, and thread_function().
proc()
void proc (char * inputfile, char * outputfile)
Definition at line 44 of file main.c.
{
 int buffer[MAX];
 FILE *fi;
 FILE *fo;
 int i=0;
 int nr=0;
 fi=fopen(inputfile, "r");
 fscanf(fi, "%d", &nr);
 for(; i<nr; i++)
     fscanf(fi, "%d", &buffer[i]);
     fclose(fi);
 buffer=sort(&buffer, nr);
 fo=fopen(outputfile, "w+");
 for(i=0; i<nr; i++)
     fprintf(fo, "%d", buffer[i]);
     return NULL;
 }
References sort().
Referenced by thread_function().
sort()
int* sort (int * buffer, int nr)
Definition at line 68 of file main.c.
{
 int i,j;
 int temp;
 for(i=0; i<nr-1; i++)
 for(j=i; j<nr; j++)
     if(buffer[i]>buffer[j]){
         temp=buffer[i];
         buffer[i]=buffer[j];
         buffer[j]=temp;
     }
 return(buffer);
 }
Referenced by proc().
thread_function()
void * thread_function (void * arg)
Definition at line 62 of file main.c.
{
     ftype *seg=(ftype *)arg;
     proc(seg->input_file, seg->output_file);
     return NULL;
     }
References file::input_file, file::output_file, and proc().
Referenced by main().
⬇️ Download 🐙 View on GitHub
© 2025 Giuseppe Pedone — GitHub