.TH "file" 3 "Tue Dec 9 2025" "CLinux" \" -*- nroff -*-
.ad l
.nh
.SH NAME
file
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char * \fBinput_file\fP"
.br
.ti -1c
.RI "char * \fBoutput_file\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 12 of file main\&.c\&.
.SH "Member Data Documentation"
.PP 
.SS "char* file::input_file"

.PP
Definition at line 12 of file main\&.c\&.
.PP
Referenced by main(), and thread_function()\&.
.SS "char* file::output_file"

.PP
Definition at line 12 of file main\&.c\&.
.PP
Referenced by main(), and thread_function()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CLinux from the source code\&.
