.TH "nf" 3 "Fri Dec 5 2025" "CLinux" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nf
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int * \fBbuf\fP"
.br
.ti -1c
.RI "char \fBfilein\fP [50]"
.br
.ti -1c
.RI "char \fBfileout\fP [50]"
.br
.ti -1c
.RI "int \fBnr\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 12 of file main\&.c\&.
.SH "Member Data Documentation"
.PP 
.SS "int* nf::buf"

.PP
Definition at line 17 of file main\&.c\&.
.PP
Referenced by bubblesort(), ReadFileIn(), and WriteFileOut()\&.
.SS "char nf::filein[50]"

.PP
Definition at line 15 of file main\&.c\&.
.PP
Referenced by main(), and ReadFileIn()\&.
.SS "char nf::fileout[50]"

.PP
Definition at line 16 of file main\&.c\&.
.PP
Referenced by main(), and WriteFileOut()\&.
.SS "int nf::nr"

.PP
Definition at line 18 of file main\&.c\&.
.PP
Referenced by bubblesort(), ReadFileIn(), and WriteFileOut()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CLinux from the source code\&.
