.TH "src/C-Unix-STD-Signal-Fork-Pause/son1.txt" 3 "Sat Dec 27 2025" "CLinux" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/C-Unix-STD-Signal-Fork-Pause/son1.txt
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "Ciao tutto \fBa\fP posto sto bene non ti preooccupare Ricordati di fare la spesa Non dimenticarti la \fBgiacca\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "Ciao tutto \fBa\fP posto sto bene non ti preooccupare Ricordati di fare la spesa Non dimenticarti la giacca"

.PP
Definition at line 2 of file son1\&.txt\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for CLinux from the source code\&.
